# importing the necessary libraries
import cv2
import numpy as np

# Creating a VideoCapture object to read the video
cap = cv2.VideoCapture('DJI_0001.MP4')


# Loop until the end of the video
while (cap.isOpened()):
	# Capture frame-by-frame
	ret, frame = cap.read()
	frame = cv2.resize(frame, (540, 380), fx = 0, fy = 0,
						interpolation = cv2.INTER_CUBIC)

	# Display the resulting frame
	cv2.imshow('Frame', frame)
	
	# conversion of BGR to grayscale is necessary to apply this operation
	gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

	_, mask = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

	# apply NOT operation on image and mask generated by thresholding
	BIT = cv2.bitwise_not(frame, frame, mask = mask)
	cv2.imshow('BIT', BIT)

	# define q as the exit button
	if cv2.waitKey(25) & 0xFF == ord('q'):
		break

# release the video capture object
cap.release()

# Closes all the windows currently opened.
cv2.destroyAllWindows()